version: "3.8"
services:
  backend:
    build: .
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
      - logs:/app/logs
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  logs: