export { default as Button } from './Button/Button';
export { default as ProjectCard } from "./ProjectCard/ProjectCard";
export { default as ProjectNavbar } from "./ProjectNavbar/ProjectNavbar";
export { default as Header } from './Header/Header';
export { default as Footer } from './Footer/Footer';
export { default as HomeSection } from './sections/HomeSection/HomeSection'
export { default as TextHighlight } from './TextHighlight/TextHightlight'
export { default as ImageScroll } from './ImageScroll/ImageScroll';
export { default as WhoAreWeSection } from './sections/WhoAreWeSection/WhoAreWeSection'
export { default as WhoAreWeSectionV2 } from './sections/WhoAreWeSection/WhoAreWeSectionV2'
export { default as FrenteCard } from './FrenteCard/FrenteCard.tsx'
export { default as FrenteSection } from './sections/FrenteSection/FrenteSection.tsx'